# Generated by Django 5.2.5 on 2025-08-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntwld', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
