# Generated by Django 5.2.5 on 2025-08-17 14:16

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntwld', '0002_client_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='content_images')),
                ('caption', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('like', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='picture',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='profile_picture'),
        ),
    ]
