# Generated by Django 5.2.5 on 2025-08-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntwld', '0003_content_alter_client_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
