# Generated by Django 5.2.5 on 2025-08-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntwld', '0004_alter_content_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(max_length=500)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
