# Generated by Django 5.2.5 on 2025-08-17 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntwld', '0005_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='username',
        ),
    ]
