# Generated by Django 5.2.5 on 2025-08-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntwld', '0007_followerscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
