# Generated by Django 5.2.5 on 2025-08-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntwld', '0009_bookmarks_content_bookmarks_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.CharField(blank=True),
        ),
    ]
