# Generated by Django 5.2.5 on 2025-08-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntwld', '0010_content_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
