# Generated by Django 5.2.5 on 2025-09-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntwld', '0011_vote_content_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, upload_to='content_images'),
        ),
    ]
